### ISSUE TITLE
Error using basic rax.py

### ISSUE THREAD

**Issue by fewknow** [rackerlabs/developer.rackspace.com#1168]
Seems to work with 

RAX_REGION=DFW ./rax.py --list
{}

but trying a different region fails.

RAX_REGION=IAD ./rax.py --list
Traceback (most recent call last):
  File "./rax.py", line 282, in <module>
    main()
  File "./rax.py", line 275, in main
    _list(regions)
  File "./rax.py", line 185, in _list
    imagegroup = 'image-%s' % images[server.image['id']]
TypeError: string indices must be integers

Any help would be great...thanks

**Comment by TodorTuparov** [comment]
I have noticed the same:
with ~/.raxpub containing region = ORD

**Comment by TodorTuparov** [comment]
main()
  File "/usr/bin/rax.py", line 461, in main
    _list(regions, refresh_cache=args.refresh_cache)
  File "/usr/bin/rax.py", line 374, in _list
    _list_into_cache(regions)
  File "/usr/bin/rax.py", line 310, in _list_into_cache
    imagegroup = 'image-%s' % images[server.image['id']]
TypeError: string indices must be integers
